import type { Metadata } from 'next'
import Sidebar from '@/components/nav/Sidebar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='hidden lg:block'>
          <Sidebar />
          {verify}
        </div>
        {children}
      </body>
    </html>
  )
}
